# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('dev', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('validation_tag', models.IntegerField()),
                ('hunted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunteds', to='auth.Group')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunters', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='date sended')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='dev.Team')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='dev.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='dev.Team'),
        ),
        migrations.AddField(
            model_name='huntedtag',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='dev.Location'),
        ),
    ]
