# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_auto_20170831_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('score', models.IntegerField()),
                ('activation_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
