# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0004_waypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_class',
            field=models.IntegerField(choices=[(0, 'Hunter'), (1, 'Hunted')], default=0),
        ),
    ]
