# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0005_team_team_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntedtag',
            name='hunted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunted', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='huntedtag',
            name='hunter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunter', to='auth.Group'),
        ),
    ]
